# https://taskfile.dev

version: "3"

tasks:
  default:
    aliases:
      - list
    desc: List all tasks
    cmd: task -l
  dev:
    desc: Start development server
    cmd: pnpm dev {{.CLI_ARGS}}
  storybook:
    desc: Start Storybook for UI component development
    cmd: pnpm storybook {{.CLI_ARGS}}
  format:
    desc: Format files
    cmd: pnpm format
  format-check:
    desc: Run format checks
    cmd: pnpm format --check
  lint:
    desc: Run lint checks
    cmd: pnpm lint --deny-warnings
  typecheck:
    desc: Run TypeScript type checks
    cmd: pnpm typecheck
  test-unit:
    desc: Run unit and integration tests
    cmd: pnpm test:unit -- --silent --reporter=dot {{.CLI_ARGS}}
  test-storybook:
    desc: Run Storybook interaction tests
    cmd: pnpm test:storybook -- --silent --reporter=dot {{.CLI_ARGS}}
  test:
    desc: Run all tests sequentially
    cmds:
      - task test-unit -- {{.CLI_ARGS}}
      - task test-storybook -- {{.CLI_ARGS}}
  verify:
    desc: Run all verification tasks sequentially
    cmds:
      - task lint
      - task format-check
      - task typecheck
      - task test-unit
      - task test-storybook
  build:
    desc: Build the application for production
    cmd: pnpm build {{.CLI_ARGS}}
