# https://taskfile.dev

version: "3"

tasks:
  default:
    aliases:
      - list
    desc: List all tasks
    cmd: task -l
  check:
    desc: Run linting and format checks
    cmd: pnpm check-write
  test:
    desc: Run tests
    cmd: pnpm test -- --silent --reporter=dot {{.CLI_ARGS}}
  dev:
    desc: Start development server
    cmd: pnpm dev -- {{.CLI_ARGS}}
  build:
    desc: Build the application for production
    cmd: pnpm build -- {{.CLI_ARGS}}
  storybook:
    desc: Start Storybook for UI component development
    cmd: pnpm storybook -- {{.CLI_ARGS}}
