package core

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// 実行の詳細は公開eventとは別に、Git common directory内へ保存する。
type privateResult struct {
	Argv   []string `json:"argv"`
	Exit   int      `json:"exit"`
	Output string   `json:"output"`
}

func commandID(argv []string) string {
	canonical := []string{}
	for _, arg := range argv {
		if arg == "-count=1" && len(argv) >= 4 && argv[0] == "go" && argv[3] == "test" {
			continue
		}
		canonical = append(canonical, arg)
	}
	return digest(canonical)
}

func decisionCommandIDs(d Decision) []string {
	if d.EvidenceVersion == 1 {
		return d.CommandIDs
	}
	ids := []string{}
	for _, argv := range d.Commands {
		ids = append(ids, commandID(argv))
	}
	return ids
}

func resultCommandID(r Result) string {
	if r.CommandID != "" {
		return r.CommandID
	}
	return commandID(r.Argv)
}

func validDigest(s string) bool {
	b, err := hex.DecodeString(s)
	return err == nil && len(b) == sha256.Size && hex.EncodeToString(b) == s
}

func (s *Store) privateEvidencePath(hash string) (string, error) {
	if !validDigest(hash) {
		return "", fmt.Errorf("invalid private evidence digest")
	}
	b, err := git(s.Root, "rev-parse", "--path-format=absolute", "--git-common-dir")
	if err != nil {
		return "", err
	}
	return filepath.Join(strings.TrimSpace(string(b)), "aidd-evidence", s.Task.ID, hash+".json"), nil
}

func (s *Store) savePrivateEvidence(value any) (string, error) {
	hash := digest(value)
	path, err := s.privateEvidencePath(hash)
	if err != nil {
		return "", err
	}
	if err = os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return "", err
	}
	b, err := json.Marshal(value)
	if err != nil {
		return "", err
	}
	if saved, err := os.ReadFile(path); err == nil {
		if string(saved) != string(b) {
			return "", fmt.Errorf("private evidence digest conflict")
		}
		return hash, nil
	}
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
	if err != nil {
		return "", err
	}
	_, err = f.Write(b)
	closeErr := f.Close()
	if err != nil {
		return "", err
	}
	return hash, closeErr
}

func (s *Store) publishDecision(d *Decision) error {
	if d.EvidenceVersion != 0 || d.PlanHash != "" || len(d.CommandIDs) != 0 {
		return fmt.Errorf("public command identities are generated by Core")
	}
	hash, err := s.savePrivateEvidence(d.Commands)
	if err != nil {
		return err
	}
	d.CommandIDs = decisionCommandIDs(*d)
	d.EvidenceVersion, d.PlanHash, d.Commands = 1, hash, nil
	return nil
}

func (s *Store) executionCommands(d Decision) ([][]string, error) {
	if d.EvidenceVersion == 0 {
		return d.Commands, nil
	}
	path, err := s.privateEvidencePath(d.PlanHash)
	if err != nil {
		return nil, err
	}
	var commands [][]string
	if err = ReadInput(path, &commands); err != nil {
		return nil, fmt.Errorf("local execution plan unavailable")
	}
	if digest(commands) != d.PlanHash || digest(decisionCommandIDs(Decision{Commands: commands})) != digest(d.CommandIDs) {
		return nil, fmt.Errorf("local execution plan does not match public identities")
	}
	return commands, nil
}

// 公開用schemaの外にあるfieldは、空やnullであっても拒否する。
func validatePublicData(kind string, raw json.RawMessage, allowLegacy bool) error {
	if kind != "decision" && kind != "verify" {
		return nil
	}
	var header struct {
		Version int `json:"evidence_version"`
	}
	if err := json.Unmarshal(raw, &header); err != nil {
		return err
	}
	if header.Version == 0 && allowLegacy {
		return nil
	}
	if header.Version != 1 {
		return fmt.Errorf("public evidence requires schema version 1")
	}
	if err := rejectDuplicateKeys(raw); err != nil {
		return err
	}

	if kind == "decision" {
		var d Decision
		if err := decode(raw, &d); err != nil {
			return err
		}
		var fields map[string]json.RawMessage
		if err := json.Unmarshal(raw, &fields); err != nil {
			return err
		}
		for key := range fields {
			switch key {
			case "summary", "paths", "rules", "intent_revision", "evidence_version", "command_ids", "plan_hash":
			default:
				return fmt.Errorf("unapproved public decision field")
			}
		}
		if !validDigest(d.PlanHash) || len(d.CommandIDs) == 0 {
			return fmt.Errorf("invalid public command plan")
		}
		for _, id := range d.CommandIDs {
			if !validDigest(id) {
				return fmt.Errorf("invalid public command identity")
			}
		}
		return nil
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(raw, &fields); err != nil {
		return err
	}
	for key := range fields {
		if key != "evidence_version" && key != "stable" && key != "results" {
			return fmt.Errorf("unapproved public verification field")
		}
	}
	var results []map[string]json.RawMessage
	if err := json.Unmarshal(fields["results"], &results); err != nil {
		return err
	}
	for _, result := range results {
		for key := range result {
			if key != "command_id" && key != "exit" && key != "evidence_hash" {
				return fmt.Errorf("unapproved public result field")
			}
		}
	}

	var v struct {
		Version int   `json:"evidence_version"`
		Stable  *bool `json:"stable"`
		Results []struct {
			CommandID    string `json:"command_id"`
			Exit         *int   `json:"exit"`
			EvidenceHash string `json:"evidence_hash"`
		} `json:"results"`
	}
	if err := decode(raw, &v); err != nil {
		return err
	}
	if v.Stable == nil || len(v.Results) == 0 {
		return fmt.Errorf("public verification results required")
	}
	for _, r := range v.Results {
		if r.Exit == nil || !validDigest(r.CommandID) || !validDigest(r.EvidenceHash) {
			return fmt.Errorf("invalid public verification identity")
		}
	}
	return nil
}

func validateResultIDs(d Decision, v Verification) error {
	ids := decisionCommandIDs(d)
	if len(ids) != len(v.Results) {
		return fmt.Errorf("verification command count mismatch")
	}
	for i, r := range v.Results {
		if resultCommandID(r) != ids[i] {
			return fmt.Errorf("unknown verification command identity")
		}
	}
	return nil
}

// 旧形式の読取と、公開し直すTaskの検査を分ける。CIにローカル証拠は不要。
func (s *Store) CheckPublicRecords() error {
	var decision Decision
	for _, event := range s.Events {
		if err := validatePublicData(event.Kind, event.Data, false); err != nil {
			return err
		}
		if event.Kind == "decision" {
			decision = eventData[Decision](&event)
		}
		if event.Kind == "verify" {
			if err := validateResultIDs(decision, eventData[Verification](&event)); err != nil {
				return err
			}
		}
	}
	return nil
}

// 同じkeyの上書きで不正な値が検査から隠れることを防ぐ。
func rejectDuplicateKeys(raw []byte) error {
	d := json.NewDecoder(strings.NewReader(string(raw)))
	var value func() error
	value = func() error {
		token, err := d.Token()
		if err != nil {
			return err
		}
		delim, ok := token.(json.Delim)
		if !ok {
			return nil
		}
		seen := map[string]bool{}
		for d.More() {
			if delim == '{' {
				key, err := d.Token()
				if err != nil {
					return err
				}
				name := key.(string)
				if seen[name] {
					return fmt.Errorf("duplicate public evidence field")
				}
				seen[name] = true
			}
			if err := value(); err != nil {
				return err
			}
		}
		_, err = d.Token()
		return err
	}
	if err := value(); err != nil {
		return err
	}
	if _, err := d.Token(); err != io.EOF {
		return fmt.Errorf("trailing public evidence data")
	}
	return nil
}
