packages:
  - apps/*
allowBuilds:
  '@sentry/cli': true
  esbuild: true
  msw: true
  sharp: true
  supabase: true
  workerd: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.1.21
  vite-plus: 0.1.21
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.21
minimumReleaseAge: 10080
overrides:
  undici@>=7.0.0 <7.24.0: "^8.0.0"
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
savePrefix: ""
