# https://taskfile.dev

version: "3"

includes:
  web:
    taskfile: apps/web/Taskfile.yml
    dir: ./apps/web
  api:
    taskfile: apps/api/Taskfile.yml
    dir: ./apps/api

tasks:
  default:
    aliases:
      - list
    desc: List all tasks
    cmd: task -l
