# https://taskfile.dev

version: "3"

dotenv: [".env"]

tasks:
  default:
    aliases:
      - list
    desc: List all tasks
    cmd: task -l
  lint:
    desc: Run linting
    cmd: deno lint
  test:
    desc: Run tests
    cmd: deno test --allow-read {{.CLI_ARGS}}
  insert:
    desc: Run the insert application
    cmd: deno run --allow-env --allow-read main.ts {{.CLI_ARGS}}
