
[auth]
site_url = "env(AUTH_SITE_URL)"
additional_redirect_urls = [
	"env(AUTH_REDIRECT_URL)",
]

[auth.external.google]
enabled = true
client_id = "env(SUPABASE_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_GOOGLE_CLIENT_SECRET)"
redirect_uri = "env(SUPABASE_GOOGLE_REDIRECT_URL)"
skip_nonce_check = "env(SUPABASE_GOOGLE_SKIP_NONCE_CHECK)"
