# https://taskfile.dev

version: "3"

tasks:
  default:
    aliases:
      - list
    desc: List all tasks
    cmd: task -l

  up:
    desc: Start Supabase locally
    cmd: npx supabase start

  down:
    desc: Stop Supabase locally
    cmd: npx supabase stop

  up:migrations:
    desc: Run database migrations to latest
    cmd: npx supabase migration up

  down:migrations:
    desc: Rollback the last database migration
    cmd: npx supabase migration down
