# https://taskfile.dev

version: "3"

tasks:
  default:
    aliases:
      - list
    desc: List all tasks
    cmd: task -l
  check:
    desc: Run linting and format checks
    cmd: npm run check:write
  dev:
    desc: Run the development server
    cmd: npm run dev
