# https://taskfile.dev

version: "3"

tasks:
  default:
    aliases:
      - list
    desc: List all tasks
    cmd: task -l

  up:
    desc: Start Supabase and serve functions locally
    cmds:
      - npx supabase start
      - task serve:functions:payments

  down:
    desc: Stop Supabase and functions
    cmds:
      - task stop:functions:payments
      - npx supabase stop

  serve:functions:payments:
    desc: Serve Supabase Edge Functions in background (daemon-like)
    cmds:
      - mkdir -p .run
      - sh -c 'nohup npx supabase functions serve payments >> .run/functions.log 2>&1 & echo $! > .run/function_payments.pid'

  stop:functions:payments:
    desc: Stop background Supabase Edge Functions
    cmds:
      - sh -c 'test -f .run/function_payments.pid && kill "$(cat .run/function_payments.pid)" || true'
      - rm -f .run/function_payments.pid

  logs:functions:payments:
    desc: Tail functions logs
    cmd: tail -f .run/functions.log
