name = "api"
main = "src/index.ts"
compatibility_date = "2025-10-10"

# Local development settings. These vars are used when running `wrangler dev --config wrangler.dev.toml`.
vars = { DB_FILE_NAME = "file:savings-dev.db" }

# If you use D1 locally with Miniflare, add d1_databases here with local database name.
# Example:
[[d1_databases]]
binding = "DB"
database_name = "savings-dev"
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
