name: Build and Push Playwright Docker Image

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/push_playwright_docker_image.yaml"
      - "docker/playwright/**"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Playwright version
        id: playwright-version
        run: |
          echo "PLAYWRIGHT_VERSION=$(cat package.json | jq -r '.dependencies.playwright')" >> $GITHUB_ENV
        working-directory: ./docker/playwright

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image for specific Playwright version
        uses: docker/build-push-action@v6
        with:
          context: docker/playwright/
          file: docker/playwright/Dockerfile
          platforms: linux/amd64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ghcr.io/${{ github.repository_owner }}/savings-playwright:${{ env.PLAYWRIGHT_VERSION }}

      - name: Build and push latest tag for latest Playwright version
        uses: docker/build-push-action@v6
        with:
          context: docker/playwright/
          file: docker/playwright/Dockerfile
          platforms: linux/amd64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ghcr.io/${{ github.repository_owner }}/savings-playwright:latest
